### PR TITLE
add toolchain file

### PR DESCRIPTION
**Pull request by guanqun**

### CODE REVIEW

**Comment by guanqun** [comment]
so you don't have to say it explicitly in README. :)

**Comment by vorot93** [comment]
Thanks for the PR!

Currently our nightly is a moving target. If (when?) we hit a bug on nightly, then we will fix the version in the toolchain file.

**Comment by guanqun** [comment]
Are you saying that we don't want this fix to be explicit? If someone else tries it with an outdated nightly, it just sliently fails.

**Comment by guanqun** [comment]
I notice that you added one in this commit: https://github.com/rust-ethereum/akula/commit/ffc3ea42da0cb2d25ceea474f6602c9e1074a1d0 ...

**Comment by vorot93** [comment]
Yes, I had to, due to rust-analyzer/rust-analyzer#8925

**Pull request closed without merging**
